<a href="https://colab.research.google.com/github/PolPetr/python-course/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%222_types_ipynb%22_%D0%9F%D0%B5%D1%82%D1%80%D0%BE%D0%B2%D0%B0_%D0%9F%D0%BE%D0%BB%D0%B8%D0%BD%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

(c) В.И. Фирсанова | 2024

# Типы данных в Python

1. **Числовые типы**:
   - `int` integer, целое число `7`
   - `float` число с плавающей точкой (десятичная дробь) `7.1`

2. **Булевы перменные**:
   - `Bool` Boolean, принимает значения `True` или `False`

3. **Наборы, последовательности**:
   - `str` string, строка `"hello"`
   - `list`, список `[1, 7.1, "hello"]`, изменяемая последовательность
    - *вложенный список* состоит из множества списков `[[0, 1, 2], [3, 4]]`
   - `tuple`, кортеж `(1, 7.1, "hello), неизменяемая последовательность
    - в кортежах нельзя удалять, добавлять данные; они занимают меньше памяти
   - `dict`, dictionary, словарь `{"number": 1, "word": "hello"}`, пары ключей и значений (key-query)
    - в этом примере ключами будут `"number"` и `"word"`, а значениями - `1` и `"hello"`
  - `set`, множество, неупорядоченный набор уникальных элементов `{1, 2, 3}`
  - `frozenset`, неизменяемое множество (аналог кортежа по отношению к спискам)

4. **None**:
   - `None` можно использовать для создания пустого элемента, как плейсхолдер в функции, для проверки факта наличия объекта в переменной и т.д.

Задачи

1. Угадай число

In [8]:
import random # библиотека для генерации случайных чисел

# генерируем случайное целое число (random integer) от 0 до 10
# функция randint принимает два аргумента: диапазон генерации
magic_number = random.randint(0, 10)

# запросите у пользователя ввод числа
user_number = int(input("Введите число от 0 до 10: "))

if user_number == magic_number: # проверка на совпадение значений
  print('Поздравляю, вы угадали!')
else:
  print('А вот и нет! Это число', magic_number)

Введите число от 0 до 10: 7
А вот и нет! Это число 5

Обратите внимание на строку `print('А вот и нет! Это число', magic_number)`

`print` может принимать несколько аргументов через запятую и выводить на экран их все!

Используйте это в следующем задании.

2. Приветствие

In [10]:
# запросите у пользователя его имя
# вспомните, чем input(int()) отличается от input()
user_name = input("Введите ваше имя: ")

# выведите на экран любое приветствие для пользователя
print("Привет, " + user_name + "!")

Введите ваше имя: Антон
Привет, Антон!

3. Конвертер температур

In [12]:
# запросите у пользователя температуру в градусах Цельсия:
# это должно быть дробное числом (float)
celsius = float(input("Введите температуру в градусах Цельсия: "))

# конвертируйте температуру из градусов Цельсия в градусы Фаренгейта:
# вспомните или найдите формулу и используйте арифметические операции python для расчетов
fahrenheit = (celsius * 1.8) + 32

# выведите результат на экран:
# используйте любые текстовые формулировки, чтобы показать число,
# которое вы получили от пользователя, и результат расчетов
print(celsius)
print(fahrenheit)

Введите температуру в градусах Цельсия: 5
5.0
41.0

Как вывести на экран несколько строк?

- Можно вызвать `print` несколько раз

```
print('Вот первая строка')
print('А это вторая строка')
```
- Можно использовать `\n` - символ новой строки

```
print('Вот первая строка \n А это вторая строка')
```

4. Округление и вывод с помощью новой строки

In [28]:
# результат расчетов в задаче 3 сохранился в переменных
# воспользуемся этим преимуществом!

# округлите оба значения температур в градусах Цельсия и в градусах Фаргентейта
# вы можете преобразовать результат к виду целого числа с помощью int(n); n - число для преобразования
# либо воспользоваться функцией round(n, k), указав в аргументах функции количество знаков после запятой k
# попробуйте оба варианта!
result_1 = int(celsius)
result_2 = int(fahrenheit)
result_3 = round(celsius, 1)
result_4 = round(fahrenheit, 1)

# теперь выведите на экран оба числа
# сделайте это в одну строчку кода:
# используйте символ новой строки, подумайте, куда его добавить
print(result_1, result_2, result_3, result_4, sep = '\n')

5
41
5.0
41.0

В задании 4 нам может помочь свойство конкатенации строк.

`print('Hello' + ' ' +'World')`

Но сложение строки с числом невозможно в питоне. Что делать?

5. Конвертирование типов данных

In [33]:
# преобразуйте округленные значения температур к виду строк, применив str(n),
# где n - то, что вы хотите преобразовать к виду строки
temperature_celsius_str = str(round(celsius))
temperature_fahrenheit_str = str(round(fahrenheit))

# выведите на экран результат:
# используйте конкатенацию строк вместо запятой в функции print
print(temperature_celsius_str + temperature_fahrenheit_str)

541

Чтобы преобразовать один тип данных в другой, мы вызываем функцию, обозначающую этот тип.

Закрепим новый материал.

6. Калькулятор

In [35]:
# запросите у пользователя 2 целых числа
# выполните операции сложения, вычитания, умножения и возведения каждого из чисел во вторую степень
# выведите результат на экран

number_1 = int(input('Введите первое число: '))
number_2 = int(input('Введите второе число: '))
result_1 = str(number_1 + number_2)
result_2 = str(number_1 - number_2)
result_3 = str(number_1 * number_2)
result_4 = str(number_1 **2)
result_5 = str(number_2 **2)
print('Результат сложения ' + result_1 + '\n' + 'Результат вычитания ' + result_2 + '\n' + 'Результат умножения ' + result_3 + '\n' + 'Результат возведения во вторую степень первого числа ' + result_4 + '\n' + 'Результат возведения во вторую степень второго числа '+ result_5  + '\n')

Введите первое число: 5
Введите второе число: 2
Результат сложения 7
Результат вычитания 3
Результат умножения 10
Результат возведения во вторую степень первого числа 25
Результат возведения во вторую степень второго числа 4

7. Анкета

In [44]:
# вспомним множественное присваивание в python
# a, b, c = 0, 1, 2
# используйте множественное присваивание,
# чтобы одной строчкой кода запросить у пользователя имя, возраст и профессию
# выведите на экран полученную информацию

name, age, profession = str(input('Ваше имя: ')), str(input('Ваш возраст: ')), str(input('Ваша профессия: '))
print(f"Имя: {name}" + '\n' + f"Возраст: {age}" + '\n' + f"Профессия: {profession}")

Ваше имя: Антон
Ваш возраст: 25
Ваша профессия: слесарь
Имя: Антон
Возраст: 25
Профессия: слесарь

8. Поменять местами переменные

In [48]:
# множественное присваивание иногда очень полезно
# запросите у пользователя две любые переменные
# это может быть строка или число, на ваш выбор

# поменяйте их местами одной строчкой кода:
# запишите в первую переменную информацию из второй,
# а во вторую переменную - информацию из первой, используя множественное присваивание

# выведите на экран промежуточные и итоговые результаты

a = input("Введите информацию в первую переменную: ")
b = input("Введите информацию во вторую переменную: ")
print("В первой переменной хранится ", a, '\n', "Во второй переменной хранится ", b )
a, b = b, a
print("В первой переменной хранится ", a, '\n', "Во второй переменной хранится ", b )

Введите информацию в первую переменную: яблоко
Введите информацию во вторую переменную: груша
В первой переменной хранится  яблоко
 Во второй переменной хранится  груша
В первой переменной хранится  груша
 Во второй переменной хранится  яблоко

9. Дописать функцию

In [49]:
# чаще мы используем множественное присваивание в фунциональном программировании
# например, эта функция считает сумму и произведение двух чисел
# функция принимает на вход (почти как input!) 2 числа
# эти числа запишутся в переменные a и b
def sum_and_product(a, b):
    # напишите здесь код для расчета суммы чисел a и b
    total_sum = a + b
    # а сюда допишите код для подсчета их произведения
    product = a * b
    # функция возвращает результат подсчета - два новых числа
    return total_sum, product

# настало время множественного присваивания
# мы вызывает функцию sum_and_product и передаем ей в качестве аргументов два числа - 5 и 3
# мы помним, что функция возвращает 2 новых числа,
# поэтому результат работы одной функции мы записываем в две переменные: result_sum и result_product
result_sum, result_product = sum_and_product(5, 3)

# выведите на экран result_sum и result_product
print(result_sum)
print(result_product)

8
15

10. Строка и число

In [55]:
# запросите у пользователя 2 числа, используйте str(input())
# сложите два числа, не меняя тип данных, и выведите на экран результат
# преобразуйте числа к виду нужного типа и снова сложите их, выведите результат

# это задание нам уже знакомо:
# попробуйте решить его питонично, используя как можно меньше строк кода
# какие операции можно объединить?
# в каких случаях нам не нужно создавать дополнительные переменные?

a, b = input("Введите число: "), input("Введите еще одно число: ")
print(a + b)
print(int(a) + int(b))

Введите число: 4
Введите еще одно число: 2
42
6